name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Back
    - run: cd Cyna-Back && npm install && npm run main
    - name: Build Front
    - run: cd Cyna-Front && npm install && npm run build --if-present
    - name: Build Back
    - run: cd Cyna-Back && npm install && npx validate

        
        
